// <auto-generated />
namespace XGame.Infra2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class MapeandoPlataforma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MapeandoPlataforma));
        
        string IMigrationMetadata.Id
        {
            get { return "201910041222228_MapeandoPlataforma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
